CREATE DATABASE IF NOT EXISTS warehouse_label;
USE warehouse_label;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(120) NULL,
  username VARCHAR(80) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nama_kategori VARCHAR(120) NOT NULL,
  supplier VARCHAR(120) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS material_stocks (
  id INT PRIMARY KEY AUTO_INCREMENT,
  tanggal DATE NOT NULL,
  no_po VARCHAR(120) NOT NULL,
  nama_material VARCHAR(120) NOT NULL,
  ukuran_panjang DECIMAL(10,2) NOT NULL,
  ukuran_lebar DECIMAL(10,2) NOT NULL,
  jumlah_roll INT DEFAULT 0,
  supplier_id INT NULL,
  kategori_id INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS label_stocks (
  id INT PRIMARY KEY AUTO_INCREMENT,
  tanggal DATE NOT NULL,
  pn_prefix VARCHAR(80) NOT NULL,
  nama_item VARCHAR(120) NOT NULL,
  ukuran_value VARCHAR(30) NULL,
  stock_awal INT NOT NULL DEFAULT 0,
  stock_total INT NOT NULL DEFAULT 0,
  finishing ENUM('FI','FO','CORELESS','FANFOLD','SHEET') NOT NULL DEFAULT 'FI',
  isi VARCHAR(80) NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Aman',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS label_masuk (
  id INT PRIMARY KEY AUTO_INCREMENT,
  tanggal DATE NOT NULL,
  no_lps VARCHAR(120) NOT NULL,
  pn VARCHAR(60) NOT NULL,
  nama_item VARCHAR(120) NOT NULL,
  ukuran VARCHAR(40) NOT NULL,
  jumlah_roll INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS label_keluar (
  id INT PRIMARY KEY AUTO_INCREMENT,
  tanggal DATE NOT NULL,
  no_sj VARCHAR(120) NOT NULL,
  pn VARCHAR(60) NOT NULL,
  nama_item VARCHAR(120) NOT NULL,
  ukuran VARCHAR(40) NOT NULL,
  jumlah_roll INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lps_docs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  no_lps VARCHAR(120) NOT NULL,
  pn VARCHAR(60) NOT NULL,
  detail_form JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sj_docs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  no_sj VARCHAR(120) NOT NULL,
  pn VARCHAR(60) NOT NULL,
  detail_form JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_settings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  setting_key VARCHAR(80) UNIQUE NOT NULL,
  setting_value TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backup_logs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  backup_name VARCHAR(160) NOT NULL,
  note VARCHAR(255) NULL,
  created_by VARCHAR(80) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, password_hash, role)
VALUES ('superadmin', '$2b$10$5DzNioIzg7BXg04vRIYzZOw7GnOrs5NMSt9fuy9JMkFDWHmRzgGfG', 'superadmin')
ON DUPLICATE KEY UPDATE role = VALUES(role);
